# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1026, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 640))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 959, 581))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.main_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.main_layout.setObjectName(_fromUtf8("main_layout"))
        self.bt_copy_all = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_copy_all.sizePolicy().hasHeightForWidth())
        self.bt_copy_all.setSizePolicy(sizePolicy)
        self.bt_copy_all.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bt_copy_all.setObjectName(_fromUtf8("bt_copy_all"))
        self.main_layout.addWidget(self.bt_copy_all, 2, 7, 1, 2)
        self.bt_last_source_page = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_last_source_page.sizePolicy().hasHeightForWidth())
        self.bt_last_source_page.setSizePolicy(sizePolicy)
        self.bt_last_source_page.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_last_source_page.setObjectName(_fromUtf8("bt_last_source_page"))
        self.main_layout.addWidget(self.bt_last_source_page, 11, 4, 1, 1)
        self.bt_prev_source_page = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_prev_source_page.sizePolicy().hasHeightForWidth())
        self.bt_prev_source_page.setSizePolicy(sizePolicy)
        self.bt_prev_source_page.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_prev_source_page.setObjectName(_fromUtf8("bt_prev_source_page"))
        self.main_layout.addWidget(self.bt_prev_source_page, 11, 2, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.main_layout.addWidget(self.label, 5, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.main_layout.addWidget(self.label_2, 6, 7, 1, 1)
        self.bt_load_source = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_load_source.sizePolicy().hasHeightForWidth())
        self.bt_load_source.setSizePolicy(sizePolicy)
        self.bt_load_source.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_load_source.setObjectName(_fromUtf8("bt_load_source"))
        self.main_layout.addWidget(self.bt_load_source, 0, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.main_layout.addItem(spacerItem, 3, 7, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem1, 10, 7, 1, 2)
        self.bt_clear = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_clear.sizePolicy().hasHeightForWidth())
        self.bt_clear.setSizePolicy(sizePolicy)
        self.bt_clear.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bt_clear.setObjectName(_fromUtf8("bt_clear"))
        self.main_layout.addWidget(self.bt_clear, 7, 7, 1, 2)
        self.bt_next_source_page = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_next_source_page.sizePolicy().hasHeightForWidth())
        self.bt_next_source_page.setSizePolicy(sizePolicy)
        self.bt_next_source_page.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_next_source_page.setObjectName(_fromUtf8("bt_next_source_page"))
        self.main_layout.addWidget(self.bt_next_source_page, 11, 3, 1, 1)
        self.check_source_grid = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check_source_grid.setObjectName(_fromUtf8("check_source_grid"))
        self.main_layout.addWidget(self.check_source_grid, 11, 5, 1, 1)
        self.spin_to = QtGui.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_to.sizePolicy().hasHeightForWidth())
        self.spin_to.setSizePolicy(sizePolicy)
        self.spin_to.setObjectName(_fromUtf8("spin_to"))
        self.main_layout.addWidget(self.spin_to, 6, 8, 1, 1)
        self.bt_copy = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_copy.sizePolicy().hasHeightForWidth())
        self.bt_copy.setSizePolicy(sizePolicy)
        self.bt_copy.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bt_copy.setObjectName(_fromUtf8("bt_copy"))
        self.main_layout.addWidget(self.bt_copy, 4, 7, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem2, 1, 7, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.main_layout.addItem(spacerItem3, 8, 7, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem4, 11, 6, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem5, 11, 9, 1, 1)
        self.bt_first_source_page = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_first_source_page.sizePolicy().hasHeightForWidth())
        self.bt_first_source_page.setSizePolicy(sizePolicy)
        self.bt_first_source_page.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_first_source_page.setObjectName(_fromUtf8("bt_first_source_page"))
        self.main_layout.addWidget(self.bt_first_source_page, 11, 1, 1, 1)
        self.spin_from = QtGui.QSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_from.sizePolicy().hasHeightForWidth())
        self.spin_from.setSizePolicy(sizePolicy)
        self.spin_from.setObjectName(_fromUtf8("spin_from"))
        self.main_layout.addWidget(self.spin_from, 5, 8, 1, 1)
        self.bt_clar_all = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_clar_all.sizePolicy().hasHeightForWidth())
        self.bt_clar_all.setSizePolicy(sizePolicy)
        self.bt_clar_all.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bt_clar_all.setObjectName(_fromUtf8("bt_clar_all"))
        self.main_layout.addWidget(self.bt_clar_all, 9, 7, 1, 2)
        self.tx_source_path = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_source_path.setEnabled(False)
        self.tx_source_path.setObjectName(_fromUtf8("tx_source_path"))
        self.main_layout.addWidget(self.tx_source_path, 0, 0, 1, 6)
        self.bt_save_target = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_save_target.sizePolicy().hasHeightForWidth())
        self.bt_save_target.setSizePolicy(sizePolicy)
        self.bt_save_target.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_save_target.setObjectName(_fromUtf8("bt_save_target"))
        self.main_layout.addWidget(self.bt_save_target, 0, 15, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.main_layout.addWidget(self.pushButton_6, 11, 10, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem6, 11, 0, 1, 1)
        self.tx_target_path = QtGui.QLineEdit(self.gridLayoutWidget)
        self.tx_target_path.setEnabled(False)
        self.tx_target_path.setObjectName(_fromUtf8("tx_target_path"))
        self.main_layout.addWidget(self.tx_target_path, 0, 9, 1, 6)
        self.pushButton_7 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.main_layout.addWidget(self.pushButton_7, 11, 13, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.main_layout.addWidget(self.pushButton_8, 11, 11, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.main_layout.addWidget(self.pushButton_9, 11, 12, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.main_layout.addWidget(self.pushButton_10, 11, 15, 1, 1)
        self.check_target_grid = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check_target_grid.setChecked(True)
        self.check_target_grid.setObjectName(_fromUtf8("check_target_grid"))
        self.main_layout.addWidget(self.check_target_grid, 11, 14, 1, 1)
        self.frame_source = QtGui.QFrame(self.gridLayoutWidget)
        self.frame_source.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_source.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_source.setObjectName(_fromUtf8("frame_source"))
        self.label_source = QtGui.QLabel(self.frame_source)
        self.label_source.setGeometry(QtCore.QRect(20, 10, 391, 481))
        self.label_source.setFrameShape(QtGui.QFrame.Box)
        self.label_source.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_source.setAlignment(QtCore.Qt.AlignCenter)
        self.label_source.setObjectName(_fromUtf8("label_source"))
        self.main_layout.addWidget(self.frame_source, 1, 0, 10, 7)
        self.frame_target = QtGui.QFrame(self.gridLayoutWidget)
        self.frame_target.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_target.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_target.setObjectName(_fromUtf8("frame_target"))
        self.label_target = QtGui.QLabel(self.frame_target)
        self.label_target.setGeometry(QtCore.QRect(10, 10, 401, 481))
        self.label_target.setFrameShape(QtGui.QFrame.Box)
        self.label_target.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_target.setAlignment(QtCore.Qt.AlignCenter)
        self.label_target.setObjectName(_fromUtf8("label_target"))
        self.main_layout.addWidget(self.frame_target, 1, 9, 10, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.tool_bar = QtGui.QToolBar(MainWindow)
        self.tool_bar.setMovable(False)
        self.tool_bar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.tool_bar.setObjectName(_fromUtf8("tool_bar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF X\'n\'Paste", None))
        self.bt_copy_all.setText(_translate("MainWindow", "Copy All", None))
        self.bt_last_source_page.setText(_translate("MainWindow", ">>", None))
        self.bt_prev_source_page.setText(_translate("MainWindow", "<", None))
        self.label.setText(_translate("MainWindow", "From", None))
        self.label_2.setText(_translate("MainWindow", "To", None))
        self.bt_load_source.setText(_translate("MainWindow", "Open", None))
        self.bt_clear.setText(_translate("MainWindow", "Clear", None))
        self.bt_next_source_page.setText(_translate("MainWindow", ">", None))
        self.check_source_grid.setText(_translate("MainWindow", "View as grid", None))
        self.bt_copy.setText(_translate("MainWindow", "Copy", None))
        self.bt_first_source_page.setText(_translate("MainWindow", "<<", None))
        self.bt_clar_all.setText(_translate("MainWindow", "Clear All", None))
        self.bt_save_target.setText(_translate("MainWindow", "Save", None))
        self.pushButton_6.setText(_translate("MainWindow", "<<", None))
        self.pushButton_7.setText(_translate("MainWindow", ">>", None))
        self.pushButton_8.setText(_translate("MainWindow", "<", None))
        self.pushButton_9.setText(_translate("MainWindow", ">", None))
        self.pushButton_10.setText(_translate("MainWindow", "Print", None))
        self.check_target_grid.setText(_translate("MainWindow", "View as grid", None))
        self.label_source.setText(_translate("MainWindow", "TextLabel", None))
        self.label_target.setText(_translate("MainWindow", "TextLabel", None))
        self.tool_bar.setWindowTitle(_translate("MainWindow", "toolBar", None))

